// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkX4OrNfAOLTkxIacHsI0k7Y-YCPnv2Rw',
    appId: '1:175105071544:web:2581e3c63938c97154d74d',
    messagingSenderId: '175105071544',
    projectId: 'producitvity-habbitapp',
    authDomain: 'producitvity-habbitapp.firebaseapp.com',
    storageBucket: 'producitvity-habbitapp.appspot.com',
    measurementId: 'G-263SS0XPG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_r4QP8sj6DkJsDFDvsTZt6XACEHvO8o',
    appId: '1:175105071544:android:e683bf6657b4403954d74d',
    messagingSenderId: '175105071544',
    projectId: 'producitvity-habbitapp',
    storageBucket: 'producitvity-habbitapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEFGEF5l38SxqGdQ2FBM0x-9rBTokLC9g',
    appId: '1:175105071544:ios:adcb876c50aac0be54d74d',
    messagingSenderId: '175105071544',
    projectId: 'producitvity-habbitapp',
    storageBucket: 'producitvity-habbitapp.appspot.com',
    iosBundleId: 'com.example.habitSpeedCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEFGEF5l38SxqGdQ2FBM0x-9rBTokLC9g',
    appId: '1:175105071544:ios:adcb876c50aac0be54d74d',
    messagingSenderId: '175105071544',
    projectId: 'producitvity-habbitapp',
    storageBucket: 'producitvity-habbitapp.appspot.com',
    iosBundleId: 'com.example.habitSpeedCode',
  );
}
